# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BigArmaCSeq <- function(pv, alpha) {
    .Call('_wsiHD_BigArmaCSeq', PACKAGE = 'wsiHD', pv, alpha)
}

BigArmaFNP <- function(pv, sHat, beta) {
    .Call('_wsiHD_BigArmaFNP', PACKAGE = 'wsiHD', pv, sHat, beta)
}

BigArmaPiHat <- function(pv, c05, c1) {
    .Call('_wsiHD_BigArmaPiHat', PACKAGE = 'wsiHD', pv, c05, c1)
}

